#!/usr/bin/bash
read -p "Enter a number please " number
if [ $number -gt 0 ]
then
    echo "$number is a positive number."
elif [ $number -lt 0 ]
then
    echo "$number is a negative number."
elif [ $number -eq 0 ]
then
    echo "$number is zero."
else
	echo "You have not entered a number."
fi
